<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Item "{0}" does not exist' => '项目"{0}"不存在',
    'Item "{0}" was successfully deleted' => '项目"{0}"删除成功',
    'Submit' => '提交',
    'Update permission' => '更新权限',
    'Update role' => '更新角色',
    'Actions' => '操作',
    'Children' => '子项目',
    'Create permission' => '新增权限',
    'Create role' => '新增角色',
    'Description' => '描述',
    'Invalid item children' => '无效子项目',
    'Item has been created' => '项目已建立',
    'Item has been updated' => '项目已更新',
    'Item name already exists' => '项目名称已存在',
    'Name' => '名称',
    'Permissions' => '权限',
    'Roles' => '角色',
    'Rule' => '规则',
    'Rule class "{0}" does not exist' => '规则类 "{0}" 不存在',
    'Rule class can not be instantiated' => '规则类必须可被实例化',
    'Rule class must extend "yii\\rbac\\Rule"' => '规则类必须扩展 "yii\\rbac\\Rule"',
    'Rule name' => '规则名称',
];
