<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Item "{0}" does not exist' => '項目"{0}"不存在',
    'Item "{0}" was successfully deleted' => '項目"{0}"刪除成功',
    'Submit' => '提交',
    'Update permission' => '更新權限',
    'Update role' => '更新角色',
    'Actions' => '操作',
    'Children' => '子項目',
    'Create permission' => '新增權限',
    'Create role' => '新增角色',
    'Description' => '描述',
    'Invalid item children' => '無效子項目',
    'Item has been created' => '項目已建立',
    'Item has been updated' => '項目已更新',
    'Item name already exists' => '項目名稱已存在',
    'Name' => '名稱',
    'Permissions' => '權限',
    'Roles' => '角色',
    'Rule' => '規則',
    'Rule class "{0}" does not exist' => '規則類 "{0}" 不存在',
    'Rule class can not be instantiated' => '規則類必須可被實例化',
    'Rule class must extend "yii\\rbac\\Rule"' => '規則類必須擴展 "yii\\rbac\\Rule"',
    'Rule name' => '規則名稱',
];
